version: 2016.0.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: AppVeyor
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: robotdotnet-wpilib.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -targetargs:".\WPILib.Tests\Output\WPILib.Tests.dll /noshadow /framework:net-4.0 " -filter:"+[WPILib*]* -[HAL*]* -[WPILib.T*]* -[WPILib.IntegrationT*]* -[NIVision*]*" -output:coverage.xml -mergeoutput -returntargetcode
- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -targetargs:".\WPILib.IntegrationTests\Output\WPILib.IntegrationTests.dll /noshadow /framework:net-4.0 " -filter:"+[WPILib*]* -[HAL*]* -[WPILib.T*]* -[WPILib.IntegrationT*]* -[NIVision*]*" -output:coverage.xml -mergeoutput

- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"

on_success:
- ps: >-
    
    If (($env:APPVEYOR_REPO_BRANCH -eq "master") -and (!$env:APPVEYOR_PULL_REQUEST_NUMBER)) {

    ./nuget install EWSoftware.SHFB -Version 2015.10.10.0 -o sbpackages

    ./nuget install EWSoftware.SHFB.NETFramework -Version 4.6 -o sbpackages

     & 'C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe' Sandcastle\SandcastleLocalBuildsOnly.shfbproj /property:Configuration=Release

    ./nuget pack "$env:APPVEYOR_BUILD_FOLDER\WPILib\WPILib.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -IncludeReferencedProjects

    ./nuget pack "$env:APPVEYOR_BUILD_FOLDER\WPILib.Extras\WPILib.Extras.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -IncludeReferencedProjects

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    }
